name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - name: Building Artifact
        run: sleep 5
      
  dev:
    runs-on: ubuntu-latest
    needs: build
    name: Dev Deployment
    environment: Dev
    steps:
      - uses: actions/checkout@v4
      - name: Deployment Started
        run: sleep 1
      - name: Deploying
        run: sleep 2
      - name: Deployment Finished
        run: sleep 1
  test:
    runs-on: ubuntu-latest
    needs: dev
    name: Test Deployment
    environment: test
    steps:
      - uses: actions/checkout@v4
      - name: Deployment Started
        run: sleep 1
      - name: Deploying
        run: sleep 2
      - name: Deployment Finished
        run: sleep 1
  stage:
    runs-on: ubuntu-latest
    needs: test
    name: Stage Deployment
    environment: stage
    steps:
      - uses: actions/checkout@v4
      - name: Deployment Started
        run: sleep 1
      - name: Deploying
        run: sleep 2
      - name: Deployment Finished
        run: sleep 1
  prod:
    runs-on: ubuntu-latest
    needs: stage
    name: Prod Deployment
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: Deployment Started
        run: sleep 1
      - name: Deploying
        run: sleep 2
      - name: Deployment Finished
        run: sleep 1
