name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - name: Building Artifact
        run: sleep 5
      
  dev:
    runs-on: ubuntu-latest
    needs: build
    name: Dev Deployment
    steps:
      - uses: actions/checkout@v4
      - name: Started Deployment
        run: echo Starting deployment to ${{ github.job }} environment.
      - name: Deploying
        run: |
          echo Deploying to ${{ github.job }} environment.
          sleep 5
      - name: Finished Deployment
        run: echo Deployment to ${{ github.job }} environment is completed.
  test:
    runs-on: ubuntu-latest
    needs: dev
    name: Test Deployment
    env:
      env_name: test
    steps:
      - uses: actions/checkout@v4
      - name: Started Deployment
        run: echo Starting deployment to $env_name environment.
      - name: Deploying
        run: |
          echo Deploying to $env_name environment.
          sleep 5
      - name: Finished Deployment
        run: echo Deployment to $env_name environment is completed.
  stage:
    runs-on: ubuntu-latest
    needs: test
    name: Stage Deployment
    env:
      env_name: stage
    steps:
      - uses: actions/checkout@v4
      - name: Started Deployment
        run: echo Starting deployment to $env_name environment.
      - name: Deploying
        run: |
          echo Deploying to $env_name environment.
          sleep 5
      - name: Finished Deployment
        run: echo Deployment to $env_name environment is completed.
  prod:
    runs-on: ubuntu-latest
    needs: stage
    name: Prod Deployment
    env:
      env_name: prod
    steps:
      - uses: actions/checkout@v4
      - name: Started Deployment
        run: echo Starting deployment to $env_name environment.
      - name: Deploying
        run: |
          echo Deploying to $env_name environment.
          sleep 5
      - name: Finished Deployment
        run: echo Deployment to $env_name environment is completed.
