name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - name: Building Artifact
        run: sleep 5
      
  dev:
    runs-on: ubuntu-latest
    needs: build
    name: Dev Deployment
    environment: Dev
    steps:
      - uses: actions/checkout@v4
      - name: Deployment Started
        run: sleep 1
      - name: Deploying
        run: sleep 2
      - name: Deployment Finished
        run: sleep 1
  test:
    runs-on: ubuntu-latest
    needs: dev
    name: Test Deployment
    env:
      env_name: test
    steps:
      - uses: actions/checkout@v4
      - name: Started Deployment
        run: echo Starting deployment to $env_name.
      - name: Deploying
        run: |
          echo Deploying to $env_name.
          sleep 5
      - name: Finished Deployment
        run: echo Deployment to $env_name is completed.
  stage:
    runs-on: ubuntu-latest
    needs: test
    name: Stage Deployment
    env:
      env_name: stage
    steps:
      - uses: actions/checkout@v4
      - name: Started Deployment
        run: echo Starting deployment to $env_name.
      - name: Deploying
        run: |
          echo Deploying to $env_name.
          sleep 5
      - name: Finished Deployment
        run: echo Deployment to $env_name is completed.
  prod:
    runs-on: ubuntu-latest
    needs: stage
    name: Prod Deployment
    env:
      env_name: prod
    steps:
      - uses: actions/checkout@v4
      - name: Started Deployment
        run: echo Starting deployment to $env_name.
      - name: Deploying
        run: |
          echo Deploying to $env_name.
          sleep 5
      - name: Finished Deployment
        run: echo Deployment to $env_name is completed.
