name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  dev:
    runs-on: ubuntu-latest
    needs: build
    name: Dev Deployment
    env:
      env_name: dev
    steps:
      - uses: actions/checkout@v4
      - name: Started
        run: echo Starting deployment to $env_name environment.
      - name: Deploying
        run: |
          echo Deploying to $env_name environment.
          sleep 5
      - name: Finished
        run: echo Deployment to $env_name environment is completed.
